import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import data from '../public/data.json'
import Link from 'next/link'

interface image{
  name: string,
  res: string,
  date: string
}

const images = data.map( (image: image)=>{
  return (
    <div
      className={styles.image}
      key={image.name}
    >
      <Link
        href={{
          pathname:'/image/[slug]',
          query: { slug: image.name, res: image.res, date: image.date },
        }}
      >
        <Image
            src={'/assets/'+image.name}
            height="300"
            width="300"
        ></Image>
      </Link>
    </div>


  )
})

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Image Viewer
        </h1>

        <p className={styles.description}>
        </p>

        <div className={styles.grid}>
          
            {images}
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
